# Generated by Django 4.0.4 on 2022-05-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'advertiser_info',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('cost', models.IntegerField()),
                ('impression', models.IntegerField()),
                ('click', models.IntegerField()),
                ('conversion', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madup.advertiser')),
            ],
            options={
                'db_table': 'advertising_data',
            },
        ),
    ]
