# Generated by Django 4.0.4 on 2022-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
